### ISSUE TITLE
Mount Effects Issues (Low Priority)

### ISSUE THREAD

**Issue by MalikPlasmaowl** [soir20/cwa-server#2]
Some of the mounts do not have all the effects for equip or dismount. Ill provide a few examples compared against a video from when the OG game was live. Uploaded to Drive as GH has 10mb limit. 

The Zephyr-G mount is not right for both the mount and dismount:
https://drive.google.com/file/d/1HNhlsUadzBDAYjA6MP4WPbVrlDrkKsCN/view?usp=drive_link

The STAP mount is missing the ring effect on dismount:
https://drive.google.com/file/d/1MUDzwpFG3kZO7UhvBHOc-cYMVpCqb6Kl/view?usp=drive_link

Grievous Speeder seemingly has no dismount effect besides a slight ring:
https://drive.google.com/file/d/1tdnKgR8fddE-zMtKytYtm-ENs_OE_ggw/view?usp=drive_link

This is a link to a resource showing all the mount types and the mount/dismount effects from when the game was live if you would like to compare the others: https://youtube.com/playlist?list=PL8sV5uvHfQVtaM4kE---bDXB0NzyFVS9S&si=KBfmYD6WM2u1iNI2

**Comment by soir20** [comment]
@MalikPlasmaowl Thanks for the detailed report. We just merged @Delta-07's PR to fix this (#3). Can you please check whether you see any inconsistencies now?

**Comment by MalikPlasmaowl** [comment]
After testing ive found: Dismount effect is FIXED across all mounts but the equip effects are still wrong on some. 

- FC-20 and sith speeder are missing the ring animation on equip
- Mandalorian speeders missing the ring effect when equipping
- BARC speeders missing the ring when equipping
- All Zephyr G and z74 speeders are missing the ring animation and have a line that runs across the screen when equipping. 

Compared to original footage these are all currently incorrect in your server. 

Thanks guys

**Comment by soir20** [comment]
#5 and #6 should fix the issues with the mount spawn effects. We noticed another issue where the hologram effect appears under the Zephyr-G mounts. However, we reviewed some OG footage, and we think that this is a bug from the OG. If you look closely at [this video](https://www.youtube.com/watch?v=-xKuB30SREY&list=PL8sV5uvHfQVtaM4kE---bDXB0NzyFVS9S&index=9&ab_channel=EnvisionDarksideGaming), you can see the hologram a bit underneath the speeder:

![image](https://github.com/soir20/cwa-server/assets/71418127/455e3bab-3b49-4952-8303-50383d8c573f)

I am going to close this issue out since everything mentioned here has been resolved. Please feel free to reopen if you notice more issues with the mount effects. Thanks for the detailed report!
